version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    # The port is exposed internally to the frontend via the Docker network
    
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      # Map port 80 on your host to port 80 in the container
      - "80:80"
    depends_on:
      - backend
